/** Complete option lists so reports can show zeros for unused choices. */
module.exports = {
  JUDGE_VERDICTS: [
    "Outstanding",
    "Crowd-pleaser",
    "Solid pour",
    "Needs work",
    "Back to the drawing board",
  ],
  FAMILIES: ["Spirit-forward", "Sour", "Long / Fizz", "Creamy", "Frozen", "Mixed"],
  PLAY_MODES: [
    { id: "campaign", label: "Bar-hop journey" },
    { id: "mixologist", label: "Mixologist" },
    { id: "endless", label: "Endless shift" },
    { id: "training", label: "Training" },
    { id: "cotd", label: "Cocktail of the Day" },
    { id: "challenge", label: "My Bar challenge" },
  ],
  HUB_CTAS: [
    { id: "journey", label: "Start the journey" },
    { id: "mix", label: "Mixologist" },
    { id: "endless", label: "Endless shift" },
    { id: "training", label: "Training" },
    { id: "cotd", label: "Cocktail of the Day" },
    { id: "badges", label: "Badges" },
    { id: "help", label: "How to play" },
    { id: "settings", label: "Settings" },
    { id: "profile", label: "Profile" },
  ],
  VENUES: [
    { id: "snug", label: "The Snug" },
    { id: "zavod", label: "Zavod" },
    { id: "cantina", label: "La Cantina" },
    { id: "aperitivo", label: "Aperitivo" },
    { id: "casa_cana", label: "Casa Caña" },
    { id: "floridita", label: "Casa Caña" },
    { id: "speakeasy", label: "Speakeasy" },
    { id: "boudoir", label: "Le Boudoir" },
    { id: "still", label: "The Still" },
    { id: "soda_fountain", label: "Soda fountain" },
    { id: "juice_bar", label: "Juice bar" },
    { id: "beach_shack", label: "Beach shack" },
  ],
  COMPLEXITIES: ["Guess", "Pour", "Mix", "Garnish", "Full bar", "Sandbox"],
  STARS: ["0", "1", "2", "3"],
  POUR_STEPS: ["glass", "ingredients", "method", "garnish"],
  LEAVE_REASONS: ["quit", "back"],
  MENU_FROM: [
    "map",
    "station",
    "mixologist",
    "mix_result",
    "settings",
    "shop",
    "badges",
    "finish",
    "endless",
    "mybar",
    "result",
    "community",
    "leaderboard",
    "recipes",
  ],
};
